name: Compile, Run and Release

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile run.exe
      run: g++ run.cpp -std=c++17 -o run.exe

    - name: Run run.exe
      run: .\run.exe

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter pandas matplotlib

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute Chart_sort.ipynb

    - name: Archive result.csv
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: result
        path: result.csv

    - name: Archive result_tables.tex
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: result_tables
        path: result_tables.tex

    - name: Archive images folder
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: images
        path: images/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.magnus_token }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: True
        prerelease: True

    - name: Upload result.csv to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.magnus_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: result.csv
        asset_name: result.csv
        asset_content_type: text/csv

    - name: Upload result_tables.tex to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.magnus_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: result_tables.tex
        asset_name: result_tables.tex
        asset_content_type: text/plain

    - name: Archive images folder
      if: success()
      run: |
        powershell Compress-Archive -Path images/* -DestinationPath images.zip

    - name: Upload images.zip to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.magnus_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: images.zip
        asset_name: images.zip
        asset_content_type: application/zip

    - name: Archive datasets folder
      if: success()
      run: |
        powershell Compress-Archive -Path datasets/* -DestinationPath datasets.zip

    - name: Upload datasets.zip to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.magnus_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: datasets.zip
        asset_name: datasets.zip
        asset_content_type: application/zip